spring:
  application:
    name: NOP
  profiles:
    active: prod
  web:
    resources:
      add-mappings: false
server:
  port: 80
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
    context-path: /api/nop/v1



