name: Update OCI Security List

on:
  push:
    branches:
      - test/oci

jobs:
  update-security-list:
    runs-on: ubuntu-latest
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Get Github Public IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Print public Ip
        run: |
          echo "Public IPv4: ${{ steps.ip.outputs.ipv4 }}"        

      - name: Install OCI CLI
        run: |
          curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh | bash -s -- --accept-all-defaults --install-dir ~/lib/oci-cli
          export PATH=~/lib/oci-cli/bin:$PATH
          echo $PATH
        shell: bash

      - name: Configure OCI CLI
        run: |
          mkdir -p ~/.oci
          echo "${{ secrets.OCI_CLI_KEY_CONTENT }}" > ~/.oci/oci_api_key.pem
          echo "[DEFAULT]
          user=${{ secrets.OCI_CLI_USER }}
          fingerprint=${{ secrets.OCI_CLI_FINGERPRINT }}
          tenancy=${{ secrets.OCI_CLI_TENANCY }}
          region=${{ secrets.OCI_CLI_REGION }}
          key_file=~/.oci/oci_api_key.pem" > ~/.oci/config

      - name: Get existing security list rules
        run: |
          ~/lib/oci-cli/bin/oci network security-list get --security-list-id ${{ secrets.OCI_CLI_SECURITYLIST_ID }} --query 'data."ingress-security-rules"' --output json > existing-rules.json
          cat existing-rules.json

      - name: Modify ingress rules
        run: |
          IP_ADDRESS="${{ steps.ip.outputs.ipv4 }}"
          NEW_RULE='{"protocol": "6", "source": "'$IP_ADDRESS'/32", "isStateless": false, "tcpOptions": {"destinationPortRange": {"min": 22, "max": 22}}}'
          jq --argjson newRule "$NEW_RULE" '. += [$newRule]' existing-rules.json > merged-ingress-rules.json
          cat merged-ingress-rules.json

      - name: Update Security List
        run: |
          ~/lib/oci-cli/bin/oci network security-list update \
            --security-list-id ${{ secrets.OCI_CLI_SECURITYLIST_ID }} \
            --ingress-security-rules file://$(pwd)/merged-ingress-rules.json \
            --force
