on:
  push: 
    branches:
    - test/deploy
jobs:    
  push_to_registry:
    name: Push Docker Image to Dokcer Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check Out the Repo
        uses: actions/checkout@v4

      - name: Create Properties File
        run: |
          echo "spring:" > ./src/main/resources/application-redis.yml
          echo "  data:" >> ./src/main/resources/application-redis.yml
          echo "  redis:" >> ./src/main/resources/application-redis.yml
          echo "    host: cannon397.duckdns.org" >> ./src/main/resources/application-redis.yml
          echo "    port: ${{ secrets.REDIS_PORT }}" >> ./src/main/resources/application-redis.yml
          echo "    password: ${{ secrets.REDIS_PASSWORD }}" >> ./src/main/resources/application-redis.yml

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set execute permisstion for Gradlew
        run: chmod +x ./gradlew
        
      - name: Build with Gradle
        run: ./gradlew build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: user/app:latest
